name: Playwright Tests

on:
  schdule:
    -cron: '30 21 * * 1-4' # Cron Jobs that we have set so our autmation will trigger at this time on GitHub Actions

  # push:   # As soon as we push code the it will start executing our Autmation as GitHub WorkFlows in GitHub Actions
  #   branches: [master] #provide the Exact branch name where you are pushing your code
  # pull_request:
  #   branches: [master] 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Enviriment to Run the Test'
        reuired: true
        default: 'QA'
        type : choice
        options:
          - QA
          - stage

jobs:
  playwright:
    runs-on: ubuntu-latest # GitHub Actions Autmatically install Ubuntu(Linux) Machine ans start executing our automation on that
    timeout-minutes: 15
    environment: ${{ github.event.inputs.environment || 'QA' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Cache Playwright Browsers
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps chromium

      - name: Install Playwright OS dependencies only (if Cached)
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install-deps chromium

      - name: Run Playwright Tests
        run: npx playwright test --project=chromium
        env:
          ENV: qa
          BASE_URL: ${{ secrets.BASE_URL }}
          USERNAME1: ${{ secrets.USERNAME1 }}
          PASSWORD1: ${{ secrets.PASSWORD1 }}
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          API_TOKEN: ${{ secrets.API_TOKEN }}

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-HTML-reports-${{ github.run_id }}
          path: reports/html-report/
          retention-days: 30

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ github.run_id }}
          path: allure-results/
          retention-days: 30